alias d='docker $*'
alias d-c='docker-compose $*'
alias d-ps='docker ps -a'
alias d-stop='docker stop $(docker ps -qa)'
alias d-rm='docker rm $(docker ps -qa)'
alias d-prune='docker system prune --all'
alias d-v-prune='docker volume prune -f'
alias d-start-dev='docker-compose -f docker-compose.yml -f docker-compose.development.yml up'
